// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type AchievementDesc = {
  id: number,
  name: string,
  description: string,
  requisites: number[],
  skillId: number,
  skillLevel: number,
  resourceDisc: number[],
  craftingDisc: number[],
  cargoDisc: number[],
  itemDisc: number[],
  collectibleRewards: number[],
  pointsReward: number,
  pctChunksDiscovered: number,
  chunksDiscovered: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace AchievementDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("requisites", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("skillId", AlgebraicType.createI32Type()),
      new ProductTypeElement("skillLevel", AlgebraicType.createI32Type()),
      new ProductTypeElement("resourceDisc", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("craftingDisc", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("cargoDisc", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("itemDisc", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("collectibleRewards", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("pointsReward", AlgebraicType.createI32Type()),
      new ProductTypeElement("pctChunksDiscovered", AlgebraicType.createF32Type()),
      new ProductTypeElement("chunksDiscovered", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: AchievementDesc): void {
    AchievementDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): AchievementDesc {
    return AchievementDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


