// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { OnlineTimestamp as __OnlineTimestamp } from "./online_timestamp_type";

export type ActiveBuff = {
  buffId: number,
  buffStartTimestamp: __OnlineTimestamp,
  buffDuration: number,
  values: number[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace ActiveBuff {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("buffId", AlgebraicType.createI32Type()),
      new ProductTypeElement("buffStartTimestamp", __OnlineTimestamp.getTypeScriptAlgebraicType()),
      new ProductTypeElement("buffDuration", AlgebraicType.createI32Type()),
      new ProductTypeElement("values", AlgebraicType.createArrayType(AlgebraicType.createF32Type())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ActiveBuff): void {
    ActiveBuff.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ActiveBuff {
    return ActiveBuff.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


