// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { OffsetCoordinatesFloat as __OffsetCoordinatesFloat } from "./offset_coordinates_float_type";

export type AiDebugState = {
  entityId: bigint,
  targetEntityId: bigint,
  currentDestination: __OffsetCoordinatesFloat,
  currentPosition: __OffsetCoordinatesFloat,
  targetPosition: __OffsetCoordinatesFloat,
  dp: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace AiDebugState {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("entityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("targetEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("currentDestination", __OffsetCoordinatesFloat.getTypeScriptAlgebraicType()),
      new ProductTypeElement("currentPosition", __OffsetCoordinatesFloat.getTypeScriptAlgebraicType()),
      new ProductTypeElement("targetPosition", __OffsetCoordinatesFloat.getTypeScriptAlgebraicType()),
      new ProductTypeElement("dp", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: AiDebugState): void {
    AiDebugState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): AiDebugState {
    return AiDebugState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


