// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace ChatChannel {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type System = { tag: "System" };
  export type Global = { tag: "Global" };
  export type Local = { tag: "Local" };
  export type Region = { tag: "Region" };
  export type Claim = { tag: "Claim" };
  export type EmpirePublic = { tag: "EmpirePublic" };
  export type EmpireInternal = { tag: "EmpireInternal" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const System = { tag: "System" };
  export const Global = { tag: "Global" };
  export const Local = { tag: "Local" };
  export const Region = { tag: "Region" };
  export const Claim = { tag: "Claim" };
  export const EmpirePublic = { tag: "EmpirePublic" };
  export const EmpireInternal = { tag: "EmpireInternal" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("System", AlgebraicType.createProductType([])),
      new SumTypeVariant("Global", AlgebraicType.createProductType([])),
      new SumTypeVariant("Local", AlgebraicType.createProductType([])),
      new SumTypeVariant("Region", AlgebraicType.createProductType([])),
      new SumTypeVariant("Claim", AlgebraicType.createProductType([])),
      new SumTypeVariant("EmpirePublic", AlgebraicType.createProductType([])),
      new SumTypeVariant("EmpireInternal", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ChatChannel): void {
      ChatChannel.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ChatChannel {
      return ChatChannel.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `ChatChannel`.
export type ChatChannel = ChatChannel.System | ChatChannel.Global | ChatChannel.Local | ChatChannel.Region | ChatChannel.Claim | ChatChannel.EmpirePublic | ChatChannel.EmpireInternal;

export default ChatChannel;

