// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DeployableDesc } from "./deployable_desc_type";
import { CsvStatEntry as __CsvStatEntry } from "./csv_stat_entry_type";
import { ExperienceStackF32 as __ExperienceStackF32 } from "./experience_stack_f_32_type";
import { DeployableType as __DeployableType } from "./deployable_type_type";
import { MovementType as __MovementType } from "./movement_type_type";
import { MovementSpeed as __MovementSpeed } from "./movement_speed_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `deployable_desc`.
 *
 * Obtain a handle from the [`deployableDesc`] property on [`RemoteTables`],
 * like `ctx.db.deployableDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.deployableDesc.on_insert(...)`.
 */
export class DeployableDescTableHandle {
  tableCache: TableCache<DeployableDesc>;

  constructor(tableCache: TableCache<DeployableDesc>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<DeployableDesc> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `deployable_desc`,
   * which allows point queries on the field of the same name
   * via the [`DeployableDescIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.deployableDesc.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `deployable_desc`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): DeployableDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `deployFromCollectibleId` unique index on the table `deployable_desc`,
   * which allows point queries on the field of the same name
   * via the [`DeployableDescDeployFromCollectibleIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.deployableDesc.deployFromCollectibleId().find(...)`.
   *
   * Get a handle on the `deployFromCollectibleId` unique index on the table `deployable_desc`.
   */
  deployFromCollectibleId = {
    // Find the subscribed row whose `deployFromCollectibleId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): DeployableDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.deployFromCollectibleId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: DeployableDesc) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: DeployableDesc) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: DeployableDesc) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: DeployableDesc) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: DeployableDesc, newRow: DeployableDesc) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: DeployableDesc, newRow: DeployableDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
