// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { CsvStatEntry as __CsvStatEntry } from "./csv_stat_entry_type";
import { ExperienceStackF32 as __ExperienceStackF32 } from "./experience_stack_f_32_type";
import { DeployableType as __DeployableType } from "./deployable_type_type";
import { MovementType as __MovementType } from "./movement_type_type";
import { MovementSpeed as __MovementSpeed } from "./movement_speed_type";

export type DeployableDesc = {
  id: number,
  name: string,
  deployFromCollectibleId: number,
  deployTime: number,
  deployableType: __DeployableType,
  pathfindingId: number,
  movementType: __MovementType,
  canEnterPortals: boolean,
  speed: __MovementSpeed[],
  usePlayerSpeedModifier: boolean,
  placeableOnLand: boolean,
  placeableInWater: boolean,
  capacity: number,
  storage: number,
  stockpile: number,
  barter: number,
  itemSlotSize: number,
  cargoSlotSize: number,
  modelAddress: string,
  stats: __CsvStatEntry[],
  playerAnimationsInDeployableSlots: number[],
  allowDriverExtract: boolean,
  allowPassengerExtract: boolean,
  showForSecsAfterOwnerLogout: number,
  allowEmoteWhileDriver: boolean,
  allowEmoteWhilePassenger: boolean,
  experiencePerProgress: __ExperienceStackF32[],
  mountingRadius: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace DeployableDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("deployFromCollectibleId", AlgebraicType.createI32Type()),
      new ProductTypeElement("deployTime", AlgebraicType.createF32Type()),
      new ProductTypeElement("deployableType", __DeployableType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("pathfindingId", AlgebraicType.createI32Type()),
      new ProductTypeElement("movementType", __MovementType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("canEnterPortals", AlgebraicType.createBoolType()),
      new ProductTypeElement("speed", AlgebraicType.createArrayType(__MovementSpeed.getTypeScriptAlgebraicType())),
      new ProductTypeElement("usePlayerSpeedModifier", AlgebraicType.createBoolType()),
      new ProductTypeElement("placeableOnLand", AlgebraicType.createBoolType()),
      new ProductTypeElement("placeableInWater", AlgebraicType.createBoolType()),
      new ProductTypeElement("capacity", AlgebraicType.createI32Type()),
      new ProductTypeElement("storage", AlgebraicType.createI32Type()),
      new ProductTypeElement("stockpile", AlgebraicType.createI32Type()),
      new ProductTypeElement("barter", AlgebraicType.createI32Type()),
      new ProductTypeElement("itemSlotSize", AlgebraicType.createI32Type()),
      new ProductTypeElement("cargoSlotSize", AlgebraicType.createI32Type()),
      new ProductTypeElement("modelAddress", AlgebraicType.createStringType()),
      new ProductTypeElement("stats", AlgebraicType.createArrayType(__CsvStatEntry.getTypeScriptAlgebraicType())),
      new ProductTypeElement("playerAnimationsInDeployableSlots", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("allowDriverExtract", AlgebraicType.createBoolType()),
      new ProductTypeElement("allowPassengerExtract", AlgebraicType.createBoolType()),
      new ProductTypeElement("showForSecsAfterOwnerLogout", AlgebraicType.createI32Type()),
      new ProductTypeElement("allowEmoteWhileDriver", AlgebraicType.createBoolType()),
      new ProductTypeElement("allowEmoteWhilePassenger", AlgebraicType.createBoolType()),
      new ProductTypeElement("experiencePerProgress", AlgebraicType.createArrayType(__ExperienceStackF32.getTypeScriptAlgebraicType())),
      new ProductTypeElement("mountingRadius", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: DeployableDesc): void {
    DeployableDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): DeployableDesc {
    return DeployableDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


