// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace DimensionType {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Unknown = { tag: "Unknown" };
  export type Overworld = { tag: "Overworld" };
  export type AncientRuin = { tag: "AncientRuin" };
  export type BuildingInterior = { tag: "BuildingInterior" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Unknown = { tag: "Unknown" };
  export const Overworld = { tag: "Overworld" };
  export const AncientRuin = { tag: "AncientRuin" };
  export const BuildingInterior = { tag: "BuildingInterior" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Unknown", AlgebraicType.createProductType([])),
      new SumTypeVariant("Overworld", AlgebraicType.createProductType([])),
      new SumTypeVariant("AncientRuin", AlgebraicType.createProductType([])),
      new SumTypeVariant("BuildingInterior", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: DimensionType): void {
      DimensionType.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): DimensionType {
      return DimensionType.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `DimensionType`.
export type DimensionType = DimensionType.Unknown | DimensionType.Overworld | DimensionType.AncientRuin | DimensionType.BuildingInterior;

export default DimensionType;

