// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { EmpireSettlementState } from "./empire_settlement_state_type";
import { OffsetCoordinatesSmallMessage as __OffsetCoordinatesSmallMessage } from "./offset_coordinates_small_message_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `empire_settlement_state`.
 *
 * Obtain a handle from the [`empireSettlementState`] property on [`RemoteTables`],
 * like `ctx.db.empireSettlementState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.empireSettlementState.on_insert(...)`.
 */
export class EmpireSettlementStateTableHandle {
  tableCache: TableCache<EmpireSettlementState>;

  constructor(tableCache: TableCache<EmpireSettlementState>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<EmpireSettlementState> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `buildingEntityId` unique index on the table `empire_settlement_state`,
   * which allows point queries on the field of the same name
   * via the [`EmpireSettlementStateBuildingEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.empireSettlementState.buildingEntityId().find(...)`.
   *
   * Get a handle on the `buildingEntityId` unique index on the table `empire_settlement_state`.
   */
  buildingEntityId = {
    // Find the subscribed row whose `buildingEntityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): EmpireSettlementState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.buildingEntityId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `claimEntityId` unique index on the table `empire_settlement_state`,
   * which allows point queries on the field of the same name
   * via the [`EmpireSettlementStateClaimEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.empireSettlementState.claimEntityId().find(...)`.
   *
   * Get a handle on the `claimEntityId` unique index on the table `empire_settlement_state`.
   */
  claimEntityId = {
    // Find the subscribed row whose `claimEntityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): EmpireSettlementState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.claimEntityId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: EmpireSettlementState) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: EmpireSettlementState) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: EmpireSettlementState) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: EmpireSettlementState) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: EmpireSettlementState, newRow: EmpireSettlementState) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: EmpireSettlementState, newRow: EmpireSettlementState) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
