// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { Rarity as __Rarity } from "./rarity_type";
import { ExperienceStackF32 as __ExperienceStackF32 } from "./experience_stack_f_32_type";
import { ProbabilisticItemStack as __ProbabilisticItemStack } from "./probabilistic_item_stack_type";

export type EnemyDesc = {
  enemyType: number,
  name: string,
  pathfindingId: number,
  targetingMatrixId: number,
  combatActionsIds: number[],
  description: string,
  minSpeed: number,
  maxSpeed: number,
  radius: number,
  awarenessDestinationThreshold: number,
  minAwarenessTickSec: number,
  maxAwarenessTickSec: number,
  maxHealth: number,
  ignoreDamage: boolean,
  healthRegenQuantity: number,
  armor: number,
  accuracy: number,
  evasion: number,
  strength: number,
  minDamage: number,
  maxDamage: number,
  cooldownMultiplier: number,
  daytimeDetectRange: number,
  daytimeAggroRange: number,
  daytimeDeaggroRange: number,
  nighttimeDetectRange: number,
  nighttimeAggroRange: number,
  nighttimeDeaggroRange: number,
  evadeRange: number,
  deaggroHealthThreshold: number,
  attackLevel: number,
  defenseLevel: number,
  prefabAddress: string,
  iconAddress: string,
  extractedItemStacks: __ProbabilisticItemStack[],
  experiencePerDamageDealt: __ExperienceStackF32[],
  tier: number,
  tag: string,
  rarity: __Rarity,
  huntable: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EnemyDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("enemyType", AlgebraicType.createI32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("pathfindingId", AlgebraicType.createI32Type()),
      new ProductTypeElement("targetingMatrixId", AlgebraicType.createI32Type()),
      new ProductTypeElement("combatActionsIds", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("minSpeed", AlgebraicType.createI32Type()),
      new ProductTypeElement("maxSpeed", AlgebraicType.createI32Type()),
      new ProductTypeElement("radius", AlgebraicType.createF32Type()),
      new ProductTypeElement("awarenessDestinationThreshold", AlgebraicType.createF32Type()),
      new ProductTypeElement("minAwarenessTickSec", AlgebraicType.createF32Type()),
      new ProductTypeElement("maxAwarenessTickSec", AlgebraicType.createF32Type()),
      new ProductTypeElement("maxHealth", AlgebraicType.createI32Type()),
      new ProductTypeElement("ignoreDamage", AlgebraicType.createBoolType()),
      new ProductTypeElement("healthRegenQuantity", AlgebraicType.createF32Type()),
      new ProductTypeElement("armor", AlgebraicType.createI32Type()),
      new ProductTypeElement("accuracy", AlgebraicType.createI32Type()),
      new ProductTypeElement("evasion", AlgebraicType.createI32Type()),
      new ProductTypeElement("strength", AlgebraicType.createI32Type()),
      new ProductTypeElement("minDamage", AlgebraicType.createI32Type()),
      new ProductTypeElement("maxDamage", AlgebraicType.createI32Type()),
      new ProductTypeElement("cooldownMultiplier", AlgebraicType.createF32Type()),
      new ProductTypeElement("daytimeDetectRange", AlgebraicType.createI32Type()),
      new ProductTypeElement("daytimeAggroRange", AlgebraicType.createI32Type()),
      new ProductTypeElement("daytimeDeaggroRange", AlgebraicType.createI32Type()),
      new ProductTypeElement("nighttimeDetectRange", AlgebraicType.createI32Type()),
      new ProductTypeElement("nighttimeAggroRange", AlgebraicType.createI32Type()),
      new ProductTypeElement("nighttimeDeaggroRange", AlgebraicType.createI32Type()),
      new ProductTypeElement("evadeRange", AlgebraicType.createI32Type()),
      new ProductTypeElement("deaggroHealthThreshold", AlgebraicType.createF32Type()),
      new ProductTypeElement("attackLevel", AlgebraicType.createI32Type()),
      new ProductTypeElement("defenseLevel", AlgebraicType.createI32Type()),
      new ProductTypeElement("prefabAddress", AlgebraicType.createStringType()),
      new ProductTypeElement("iconAddress", AlgebraicType.createStringType()),
      new ProductTypeElement("extractedItemStacks", AlgebraicType.createArrayType(__ProbabilisticItemStack.getTypeScriptAlgebraicType())),
      new ProductTypeElement("experiencePerDamageDealt", AlgebraicType.createArrayType(__ExperienceStackF32.getTypeScriptAlgebraicType())),
      new ProductTypeElement("tier", AlgebraicType.createI32Type()),
      new ProductTypeElement("tag", AlgebraicType.createStringType()),
      new ProductTypeElement("rarity", __Rarity.getTypeScriptAlgebraicType()),
      new ProductTypeElement("huntable", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EnemyDesc): void {
    EnemyDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EnemyDesc {
    return EnemyDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


