// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { EntityType as __EntityType } from "./entity_type_type";

export type EntityAttackRequest = {
  attackerEntityId: bigint,
  defenderEntityId: bigint,
  combatActionId: number,
  attackerType: __EntityType,
  defenderType: __EntityType,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EntityAttackRequest {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("attackerEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("defenderEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("combatActionId", AlgebraicType.createI32Type()),
      new ProductTypeElement("attackerType", __EntityType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("defenderType", __EntityType.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EntityAttackRequest): void {
    EntityAttackRequest.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EntityAttackRequest {
    return EntityAttackRequest.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


