// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { EquipmentDesc } from "./equipment_desc_type";
import { CsvStatEntry as __CsvStatEntry } from "./csv_stat_entry_type";
import { LevelRequirement as __LevelRequirement } from "./level_requirement_type";
import { EquipmentSlotType as __EquipmentSlotType } from "./equipment_slot_type_type";
import { EquipmentVisualType as __EquipmentVisualType } from "./equipment_visual_type_type";
import { ClothingVisual as __ClothingVisual } from "./clothing_visual_type";
import { HandEquipmentVisual as __HandEquipmentVisual } from "./hand_equipment_visual_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `equipment_desc`.
 *
 * Obtain a handle from the [`equipmentDesc`] property on [`RemoteTables`],
 * like `ctx.db.equipmentDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.equipmentDesc.on_insert(...)`.
 */
export class EquipmentDescTableHandle {
  tableCache: TableCache<EquipmentDesc>;

  constructor(tableCache: TableCache<EquipmentDesc>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<EquipmentDesc> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `itemId` unique index on the table `equipment_desc`,
   * which allows point queries on the field of the same name
   * via the [`EquipmentDescItemIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.equipmentDesc.itemId().find(...)`.
   *
   * Get a handle on the `itemId` unique index on the table `equipment_desc`.
   */
  itemId = {
    // Find the subscribed row whose `itemId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): EquipmentDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.itemId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: EquipmentDesc) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: EquipmentDesc) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: EquipmentDesc) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: EquipmentDesc) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: EquipmentDesc, newRow: EquipmentDesc) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: EquipmentDesc, newRow: EquipmentDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
