// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { LevelRequirement as __LevelRequirement } from "./level_requirement_type";
import { ToolRequirement as __ToolRequirement } from "./tool_requirement_type";
import { InputItemStack as __InputItemStack } from "./input_item_stack_type";
import { ExperienceStackF32 as __ExperienceStackF32 } from "./experience_stack_f_32_type";
import { ProbabilisticItemStack as __ProbabilisticItemStack } from "./probabilistic_item_stack_type";

export type ExtractionRecipeDesc = {
  id: number,
  resourceId: number,
  cargoId: number,
  discoveryTriggers: number[],
  requiredKnowledges: number[],
  timeRequirement: number,
  staminaRequirement: number,
  toolDurabilityLost: number,
  extractedItemStacks: __ProbabilisticItemStack[],
  consumedItemStacks: __InputItemStack[],
  range: number,
  toolRequirements: __ToolRequirement[],
  allowUseHands: boolean,
  levelRequirements: __LevelRequirement[],
  experiencePerProgress: __ExperienceStackF32[],
  verbPhrase: string,
  toolMeshIndex: number,
  recipePerformanceId: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ExtractionRecipeDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("resourceId", AlgebraicType.createI32Type()),
      new ProductTypeElement("cargoId", AlgebraicType.createI32Type()),
      new ProductTypeElement("discoveryTriggers", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("requiredKnowledges", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("timeRequirement", AlgebraicType.createF32Type()),
      new ProductTypeElement("staminaRequirement", AlgebraicType.createF32Type()),
      new ProductTypeElement("toolDurabilityLost", AlgebraicType.createI32Type()),
      new ProductTypeElement("extractedItemStacks", AlgebraicType.createArrayType(__ProbabilisticItemStack.getTypeScriptAlgebraicType())),
      new ProductTypeElement("consumedItemStacks", AlgebraicType.createArrayType(__InputItemStack.getTypeScriptAlgebraicType())),
      new ProductTypeElement("range", AlgebraicType.createI32Type()),
      new ProductTypeElement("toolRequirements", AlgebraicType.createArrayType(__ToolRequirement.getTypeScriptAlgebraicType())),
      new ProductTypeElement("allowUseHands", AlgebraicType.createBoolType()),
      new ProductTypeElement("levelRequirements", AlgebraicType.createArrayType(__LevelRequirement.getTypeScriptAlgebraicType())),
      new ProductTypeElement("experiencePerProgress", AlgebraicType.createArrayType(__ExperienceStackF32.getTypeScriptAlgebraicType())),
      new ProductTypeElement("verbPhrase", AlgebraicType.createStringType()),
      new ProductTypeElement("toolMeshIndex", AlgebraicType.createI32Type()),
      new ProductTypeElement("recipePerformanceId", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ExtractionRecipeDesc): void {
    ExtractionRecipeDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ExtractionRecipeDesc {
    return ExtractionRecipeDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


