// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { BuffEffect as __BuffEffect } from "./buff_effect_type";

export type FoodDesc = {
  itemId: number,
  hp: number,
  upToHp: number,
  stamina: number,
  upToStamina: number,
  hunger: number,
  teleportationEnergy: number,
  consumableWhileInCombat: boolean,
  buffs: __BuffEffect[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace FoodDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("itemId", AlgebraicType.createI32Type()),
      new ProductTypeElement("hp", AlgebraicType.createF32Type()),
      new ProductTypeElement("upToHp", AlgebraicType.createF32Type()),
      new ProductTypeElement("stamina", AlgebraicType.createF32Type()),
      new ProductTypeElement("upToStamina", AlgebraicType.createF32Type()),
      new ProductTypeElement("hunger", AlgebraicType.createF32Type()),
      new ProductTypeElement("teleportationEnergy", AlgebraicType.createF32Type()),
      new ProductTypeElement("consumableWhileInCombat", AlgebraicType.createBoolType()),
      new ProductTypeElement("buffs", AlgebraicType.createArrayType(__BuffEffect.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: FoodDesc): void {
    FoodDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): FoodDesc {
    return FoodDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


