// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type HexiteExchangeEntryDesc = {
  id: number,
  imageAddress: string,
  shardAmount: number,
  baseShardAmount: number,
  name: string,
  price: number,
  eventName: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace HexiteExchangeEntryDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("imageAddress", AlgebraicType.createStringType()),
      new ProductTypeElement("shardAmount", AlgebraicType.createU32Type()),
      new ProductTypeElement("baseShardAmount", AlgebraicType.createU32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("price", AlgebraicType.createF32Type()),
      new ProductTypeElement("eventName", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: HexiteExchangeEntryDesc): void {
    HexiteExchangeEntryDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): HexiteExchangeEntryDesc {
    return HexiteExchangeEntryDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


