// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { InteriorSpawnDesc } from "./interior_spawn_desc_type";
import { NpcType as __NpcType } from "./npc_type_type";
import { EnemyType as __EnemyType } from "./enemy_type_type";
import { InteriorSpawnType as __InteriorSpawnType } from "./interior_spawn_type_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `interior_spawn_desc`.
 *
 * Obtain a handle from the [`interiorSpawnDesc`] property on [`RemoteTables`],
 * like `ctx.db.interiorSpawnDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.interiorSpawnDesc.on_insert(...)`.
 */
export class InteriorSpawnDescTableHandle {
  tableCache: TableCache<InteriorSpawnDesc>;

  constructor(tableCache: TableCache<InteriorSpawnDesc>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<InteriorSpawnDesc> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `interior_spawn_desc`,
   * which allows point queries on the field of the same name
   * via the [`InteriorSpawnDescIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.interiorSpawnDesc.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `interior_spawn_desc`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): InteriorSpawnDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: InteriorSpawnDesc) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: InteriorSpawnDesc) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: InteriorSpawnDesc) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: InteriorSpawnDesc) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: InteriorSpawnDesc, newRow: InteriorSpawnDesc) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: InteriorSpawnDesc, newRow: InteriorSpawnDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
