// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { NpcType as __NpcType } from "./npc_type_type";
import { EnemyType as __EnemyType } from "./enemy_type_type";
import { InteriorSpawnType as __InteriorSpawnType } from "./interior_spawn_type_type";

export type InteriorSpawnDesc = {
  id: number,
  name: string,
  interiorInstanceId: number,
  spawnX: number,
  spawnZ: number,
  direction: number,
  spawnType: __InteriorSpawnType,
  buildingId: number,
  pavingId: number,
  lootChests: number[],
  resourceClumpId: number,
  enemyType: __EnemyType,
  travelerType: __NpcType,
  travelerRuinEntityId: number,
  respawn: boolean,
  collapseTrigger: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace InteriorSpawnDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("interiorInstanceId", AlgebraicType.createI32Type()),
      new ProductTypeElement("spawnX", AlgebraicType.createI32Type()),
      new ProductTypeElement("spawnZ", AlgebraicType.createI32Type()),
      new ProductTypeElement("direction", AlgebraicType.createI32Type()),
      new ProductTypeElement("spawnType", __InteriorSpawnType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("buildingId", AlgebraicType.createI32Type()),
      new ProductTypeElement("pavingId", AlgebraicType.createI32Type()),
      new ProductTypeElement("lootChests", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
      new ProductTypeElement("resourceClumpId", AlgebraicType.createI32Type()),
      new ProductTypeElement("enemyType", __EnemyType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("travelerType", __NpcType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("travelerRuinEntityId", AlgebraicType.createI32Type()),
      new ProductTypeElement("respawn", AlgebraicType.createBoolType()),
      new ProductTypeElement("collapseTrigger", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: InteriorSpawnDesc): void {
    InteriorSpawnDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): InteriorSpawnDesc {
    return InteriorSpawnDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


