// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { FootprintTile as __FootprintTile } from "./footprint_tile_type";

export type InteriorShapeDesc = {
  id: number,
  footprint: __FootprintTile[],
  minX: number,
  minZ: number,
  sizeX: number,
  sizeZ: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace InteriorShapeDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("footprint", AlgebraicType.createArrayType(__FootprintTile.getTypeScriptAlgebraicType())),
      new ProductTypeElement("minX", AlgebraicType.createI32Type()),
      new ProductTypeElement("minZ", AlgebraicType.createI32Type()),
      new ProductTypeElement("sizeX", AlgebraicType.createI32Type()),
      new ProductTypeElement("sizeZ", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: InteriorShapeDesc): void {
    InteriorShapeDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): InteriorShapeDesc {
    return InteriorShapeDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


