// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { LocationCache } from "./location_cache_type";
import { SmallHexTileMessage as __SmallHexTileMessage } from "./small_hex_tile_message_type";
import { RuinsEntityValuePair as __RuinsEntityValuePair } from "./ruins_entity_value_pair_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `location_cache`.
 *
 * Obtain a handle from the [`locationCache`] property on [`RemoteTables`],
 * like `ctx.db.locationCache`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.locationCache.on_insert(...)`.
 */
export class LocationCacheTableHandle {
  tableCache: TableCache<LocationCache>;

  constructor(tableCache: TableCache<LocationCache>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<LocationCache> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `version` unique index on the table `location_cache`,
   * which allows point queries on the field of the same name
   * via the [`LocationCacheVersionUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.locationCache.version().find(...)`.
   *
   * Get a handle on the `version` unique index on the table `location_cache`.
   */
  version = {
    // Find the subscribed row whose `version` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): LocationCache | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.version, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: LocationCache) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: LocationCache) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: LocationCache) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: LocationCache) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: LocationCache, newRow: LocationCache) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: LocationCache, newRow: LocationCache) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
