// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type NpcDesc = {
  npcType: number,
  name: string,
  population: number,
  speed: number,
  minTimeAtRuin: number,
  maxTimeAtRuin: number,
  prefabAddress: string,
  iconAddress: string,
  forceMarketMode: boolean,
  taskSkillCheck: number[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace NpcDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("npcType", AlgebraicType.createI32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("population", AlgebraicType.createF32Type()),
      new ProductTypeElement("speed", AlgebraicType.createI32Type()),
      new ProductTypeElement("minTimeAtRuin", AlgebraicType.createI32Type()),
      new ProductTypeElement("maxTimeAtRuin", AlgebraicType.createI32Type()),
      new ProductTypeElement("prefabAddress", AlgebraicType.createStringType()),
      new ProductTypeElement("iconAddress", AlgebraicType.createStringType()),
      new ProductTypeElement("forceMarketMode", AlgebraicType.createBoolType()),
      new ProductTypeElement("taskSkillCheck", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: NpcDesc): void {
    NpcDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): NpcDesc {
    return NpcDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


