// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PassiveCraftTimer } from "./passive_craft_timer_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `passive_craft_timer`.
 *
 * Obtain a handle from the [`passiveCraftTimer`] property on [`RemoteTables`],
 * like `ctx.db.passiveCraftTimer`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.passiveCraftTimer.on_insert(...)`.
 */
export class PassiveCraftTimerTableHandle {
  tableCache: TableCache<PassiveCraftTimer>;

  constructor(tableCache: TableCache<PassiveCraftTimer>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<PassiveCraftTimer> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `scheduledId` unique index on the table `passive_craft_timer`,
   * which allows point queries on the field of the same name
   * via the [`PassiveCraftTimerScheduledIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.passiveCraftTimer.scheduledId().find(...)`.
   *
   * Get a handle on the `scheduledId` unique index on the table `passive_craft_timer`.
   */
  scheduledId = {
    // Find the subscribed row whose `scheduledId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): PassiveCraftTimer | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.scheduledId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `craftEntityId` unique index on the table `passive_craft_timer`,
   * which allows point queries on the field of the same name
   * via the [`PassiveCraftTimerCraftEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.passiveCraftTimer.craftEntityId().find(...)`.
   *
   * Get a handle on the `craftEntityId` unique index on the table `passive_craft_timer`.
   */
  craftEntityId = {
    // Find the subscribed row whose `craftEntityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): PassiveCraftTimer | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.craftEntityId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: PassiveCraftTimer) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: PassiveCraftTimer) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: PassiveCraftTimer) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: PassiveCraftTimer) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: PassiveCraftTimer, newRow: PassiveCraftTimer) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: PassiveCraftTimer, newRow: PassiveCraftTimer) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
