// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type PlayerClaimAddRecruitmentRequest = {
  claimEntityId: bigint,
  stock: number,
  requiredSkillId: number,
  requiredSkillLevel: number,
  requiredApproval: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerClaimAddRecruitmentRequest {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("claimEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("stock", AlgebraicType.createI32Type()),
      new ProductTypeElement("requiredSkillId", AlgebraicType.createI32Type()),
      new ProductTypeElement("requiredSkillLevel", AlgebraicType.createI32Type()),
      new ProductTypeElement("requiredApproval", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PlayerClaimAddRecruitmentRequest): void {
    PlayerClaimAddRecruitmentRequest.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PlayerClaimAddRecruitmentRequest {
    return PlayerClaimAddRecruitmentRequest.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


