// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { OffsetCoordinatesFloat as __OffsetCoordinatesFloat } from "./offset_coordinates_float_type";

export type PlayerMoveRequest = {
  timestamp: bigint,
  destination: __OffsetCoordinatesFloat | undefined,
  origin: __OffsetCoordinatesFloat | undefined,
  duration: number,
  moveType: number,
  running: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerMoveRequest {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("timestamp", AlgebraicType.createU64Type()),
      new ProductTypeElement("destination", AlgebraicType.createOptionType(__OffsetCoordinatesFloat.getTypeScriptAlgebraicType())),
      new ProductTypeElement("origin", AlgebraicType.createOptionType(__OffsetCoordinatesFloat.getTypeScriptAlgebraicType())),
      new ProductTypeElement("duration", AlgebraicType.createF32Type()),
      new ProductTypeElement("moveType", AlgebraicType.createI32Type()),
      new ProductTypeElement("running", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PlayerMoveRequest): void {
    PlayerMoveRequest.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PlayerMoveRequest {
    return PlayerMoveRequest.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


