// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ItemStack as __ItemStack } from "./item_stack_type";

export type PlayerBarterStallOrderCreateRequest = {
  shopEntityId: bigint,
  remainingStock: number,
  offerItems: __ItemStack | undefined,
  offerCargoId: number,
  requiredItems: __ItemStack[],
  requiredCargos: number[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerBarterStallOrderCreateRequest {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("shopEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("remainingStock", AlgebraicType.createI32Type()),
      new ProductTypeElement("offerItems", AlgebraicType.createOptionType(__ItemStack.getTypeScriptAlgebraicType())),
      new ProductTypeElement("offerCargoId", AlgebraicType.createI32Type()),
      new ProductTypeElement("requiredItems", AlgebraicType.createArrayType(__ItemStack.getTypeScriptAlgebraicType())),
      new ProductTypeElement("requiredCargos", AlgebraicType.createArrayType(AlgebraicType.createI32Type())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PlayerBarterStallOrderCreateRequest): void {
    PlayerBarterStallOrderCreateRequest.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PlayerBarterStallOrderCreateRequest {
    return PlayerBarterStallOrderCreateRequest.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


