// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { SingleResourceClumpInfo } from "./single_resource_clump_info_type";
import { ResourceClumpInfo as __ResourceClumpInfo } from "./resource_clump_info_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `single_resource_clump_info`.
 *
 * Obtain a handle from the [`singleResourceClumpInfo`] property on [`RemoteTables`],
 * like `ctx.db.singleResourceClumpInfo`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.singleResourceClumpInfo.on_insert(...)`.
 */
export class SingleResourceClumpInfoTableHandle {
  tableCache: TableCache<SingleResourceClumpInfo>;

  constructor(tableCache: TableCache<SingleResourceClumpInfo>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<SingleResourceClumpInfo> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `clumpId` unique index on the table `single_resource_clump_info`,
   * which allows point queries on the field of the same name
   * via the [`SingleResourceClumpInfoClumpIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.singleResourceClumpInfo.clumpId().find(...)`.
   *
   * Get a handle on the `clumpId` unique index on the table `single_resource_clump_info`.
   */
  clumpId = {
    // Find the subscribed row whose `clumpId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): SingleResourceClumpInfo | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.clumpId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: SingleResourceClumpInfo) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: SingleResourceClumpInfo) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: SingleResourceClumpInfo) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: SingleResourceClumpInfo) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: SingleResourceClumpInfo, newRow: SingleResourceClumpInfo) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: SingleResourceClumpInfo, newRow: SingleResourceClumpInfo) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
