// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace TeleportLocationType {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type BirthLocation = { tag: "BirthLocation" };
  export type TradingPost = { tag: "TradingPost" };
  export type HomeLocation = { tag: "HomeLocation" };
  export type CustomLocation = { tag: "CustomLocation" };
  export type Waystone = { tag: "Waystone" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const BirthLocation = { tag: "BirthLocation" };
  export const TradingPost = { tag: "TradingPost" };
  export const HomeLocation = { tag: "HomeLocation" };
  export const CustomLocation = { tag: "CustomLocation" };
  export const Waystone = { tag: "Waystone" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("BirthLocation", AlgebraicType.createProductType([])),
      new SumTypeVariant("TradingPost", AlgebraicType.createProductType([])),
      new SumTypeVariant("HomeLocation", AlgebraicType.createProductType([])),
      new SumTypeVariant("CustomLocation", AlgebraicType.createProductType([])),
      new SumTypeVariant("Waystone", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: TeleportLocationType): void {
      TeleportLocationType.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): TeleportLocationType {
      return TeleportLocationType.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `TeleportLocationType`.
export type TeleportLocationType = TeleportLocationType.BirthLocation | TeleportLocationType.TradingPost | TeleportLocationType.HomeLocation | TeleportLocationType.CustomLocation | TeleportLocationType.Waystone;

export default TeleportLocationType;

