// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { TerraformRecipeDesc } from "./terraform_recipe_desc_type";
import { ToolRequirement as __ToolRequirement } from "./tool_requirement_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `terraform_recipe_desc`.
 *
 * Obtain a handle from the [`terraformRecipeDesc`] property on [`RemoteTables`],
 * like `ctx.db.terraformRecipeDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.terraformRecipeDesc.on_insert(...)`.
 */
export class TerraformRecipeDescTableHandle {
  tableCache: TableCache<TerraformRecipeDesc>;

  constructor(tableCache: TableCache<TerraformRecipeDesc>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<TerraformRecipeDesc> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `difference` unique index on the table `terraform_recipe_desc`,
   * which allows point queries on the field of the same name
   * via the [`TerraformRecipeDescDifferenceUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.terraformRecipeDesc.difference().find(...)`.
   *
   * Get a handle on the `difference` unique index on the table `terraform_recipe_desc`.
   */
  difference = {
    // Find the subscribed row whose `difference` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): TerraformRecipeDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.difference, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: TerraformRecipeDesc) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: TerraformRecipeDesc) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: TerraformRecipeDesc) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: TerraformRecipeDesc) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: TerraformRecipeDesc, newRow: TerraformRecipeDesc) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: TerraformRecipeDesc, newRow: TerraformRecipeDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
