// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ToolRequirement as __ToolRequirement } from "./tool_requirement_type";

export type TerraformRecipeDesc = {
  difference: number,
  actionsCount: number,
  toolRequirement: __ToolRequirement | undefined,
  staminaPerAction: number,
  timePerAction: number,
  toolMeshIndex: number,
  recipePerformanceId: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace TerraformRecipeDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("difference", AlgebraicType.createI16Type()),
      new ProductTypeElement("actionsCount", AlgebraicType.createI32Type()),
      new ProductTypeElement("toolRequirement", AlgebraicType.createOptionType(__ToolRequirement.getTypeScriptAlgebraicType())),
      new ProductTypeElement("staminaPerAction", AlgebraicType.createF32Type()),
      new ProductTypeElement("timePerAction", AlgebraicType.createF32Type()),
      new ProductTypeElement("toolMeshIndex", AlgebraicType.createI32Type()),
      new ProductTypeElement("recipePerformanceId", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: TerraformRecipeDesc): void {
    TerraformRecipeDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): TerraformRecipeDesc {
    return TerraformRecipeDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


