// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ToolTypeDesc } from "./tool_type_desc_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `tool_type_desc`.
 *
 * Obtain a handle from the [`toolTypeDesc`] property on [`RemoteTables`],
 * like `ctx.db.toolTypeDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.toolTypeDesc.on_insert(...)`.
 */
export class ToolTypeDescTableHandle {
  tableCache: TableCache<ToolTypeDesc>;

  constructor(tableCache: TableCache<ToolTypeDesc>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ToolTypeDesc> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `tool_type_desc`,
   * which allows point queries on the field of the same name
   * via the [`ToolTypeDescIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.toolTypeDesc.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `tool_type_desc`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): ToolTypeDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `skillId` unique index on the table `tool_type_desc`,
   * which allows point queries on the field of the same name
   * via the [`ToolTypeDescSkillIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.toolTypeDesc.skillId().find(...)`.
   *
   * Get a handle on the `skillId` unique index on the table `tool_type_desc`.
   */
  skillId = {
    // Find the subscribed row whose `skillId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): ToolTypeDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.skillId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ToolTypeDesc) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ToolTypeDesc) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ToolTypeDesc) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ToolTypeDesc) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ToolTypeDesc, newRow: ToolTypeDesc) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ToolTypeDesc, newRow: ToolTypeDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
