// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { WorldGenLandShapeDefinition as __WorldGenLandShapeDefinition } from "./world_gen_land_shape_definition_type";

export type WorldGenWorldMapDefinition = {
  debugStep: number,
  shapes: __WorldGenLandShapeDefinition[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace WorldGenWorldMapDefinition {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("debugStep", AlgebraicType.createI32Type()),
      new ProductTypeElement("shapes", AlgebraicType.createArrayType(__WorldGenLandShapeDefinition.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: WorldGenWorldMapDefinition): void {
    WorldGenWorldMapDefinition.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): WorldGenWorldMapDefinition {
    return WorldGenWorldMapDefinition.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


