// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { WorldGenNoiseSpecs as __WorldGenNoiseSpecs } from "./world_gen_noise_specs_type";
import { WorldGenVector2 as __WorldGenVector2 } from "./world_gen_vector_2_type";

export type WorldGenResourceBiome = {
  biomeDefinitionIndex: number,
  chance: number,
  noiseThreshold: __WorldGenVector2,
  noiseSpecs: __WorldGenNoiseSpecs,
};

/**
 * A namespace for generated helper functions.
 */
export namespace WorldGenResourceBiome {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("biomeDefinitionIndex", AlgebraicType.createI32Type()),
      new ProductTypeElement("chance", AlgebraicType.createF32Type()),
      new ProductTypeElement("noiseThreshold", __WorldGenVector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("noiseSpecs", __WorldGenNoiseSpecs.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: WorldGenResourceBiome): void {
    WorldGenResourceBiome.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): WorldGenResourceBiome {
    return WorldGenResourceBiome.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


