// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ResourceState as __ResourceState } from "./resource_state_type";

export type WorldGenGeneratedResourceDeposit = {
  x: number,
  z: number,
  deposit: __ResourceState | undefined,
  dimension: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace WorldGenGeneratedResourceDeposit {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("x", AlgebraicType.createI32Type()),
      new ProductTypeElement("z", AlgebraicType.createI32Type()),
      new ProductTypeElement("deposit", AlgebraicType.createOptionType(__ResourceState.getTypeScriptAlgebraicType())),
      new ProductTypeElement("dimension", AlgebraicType.createU32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: WorldGenGeneratedResourceDeposit): void {
    WorldGenGeneratedResourceDeposit.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): WorldGenGeneratedResourceDeposit {
    return WorldGenGeneratedResourceDeposit.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


