// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { WorldGenVector2Int as __WorldGenVector2Int } from "./world_gen_vector_2_int_type";

export type WorldGenRiverPathfindingCosts = {
  elevationDifferenceRange: __WorldGenVector2Int,
  pathfindingCosts: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace WorldGenRiverPathfindingCosts {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("elevationDifferenceRange", __WorldGenVector2Int.getTypeScriptAlgebraicType()),
      new ProductTypeElement("pathfindingCosts", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: WorldGenRiverPathfindingCosts): void {
    WorldGenRiverPathfindingCosts.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): WorldGenRiverPathfindingCosts {
    return WorldGenRiverPathfindingCosts.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


