// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { WorldGenVector2Int as __WorldGenVector2Int } from "./world_gen_vector_2_int_type";
import { WorldGenAnimationCurve as __WorldGenAnimationCurve } from "./world_gen_animation_curve_type";
import { WorldGenWorldMapDefinition as __WorldGenWorldMapDefinition } from "./world_gen_world_map_definition_type";
import { WorldGenBiomesMapDefinition as __WorldGenBiomesMapDefinition } from "./world_gen_biomes_map_definition_type";
import { WorldGenMountainsMapDefinition as __WorldGenMountainsMapDefinition } from "./world_gen_mountains_map_definition_type";
import { WorldGenBuildingsMapDefinition as __WorldGenBuildingsMapDefinition } from "./world_gen_buildings_map_definition_type";
import { WorldGenResourcesMapDefinition as __WorldGenResourcesMapDefinition } from "./world_gen_resources_map_definition_type";

export type WorldGenWorldDefinition = {
  size: __WorldGenVector2Int,
  landCurve: __WorldGenAnimationCurve,
  noiseInfluence: number,
  seaLevel: number,
  worldMap: __WorldGenWorldMapDefinition,
  biomesMap: __WorldGenBiomesMapDefinition,
  mountainsMap: __WorldGenMountainsMapDefinition,
  buildingsMap: __WorldGenBuildingsMapDefinition,
  resourcesMap: __WorldGenResourcesMapDefinition,
};

/**
 * A namespace for generated helper functions.
 */
export namespace WorldGenWorldDefinition {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("size", __WorldGenVector2Int.getTypeScriptAlgebraicType()),
      new ProductTypeElement("landCurve", __WorldGenAnimationCurve.getTypeScriptAlgebraicType()),
      new ProductTypeElement("noiseInfluence", AlgebraicType.createF32Type()),
      new ProductTypeElement("seaLevel", AlgebraicType.createI32Type()),
      new ProductTypeElement("worldMap", __WorldGenWorldMapDefinition.getTypeScriptAlgebraicType()),
      new ProductTypeElement("biomesMap", __WorldGenBiomesMapDefinition.getTypeScriptAlgebraicType()),
      new ProductTypeElement("mountainsMap", __WorldGenMountainsMapDefinition.getTypeScriptAlgebraicType()),
      new ProductTypeElement("buildingsMap", __WorldGenBuildingsMapDefinition.getTypeScriptAlgebraicType()),
      new ProductTypeElement("resourcesMap", __WorldGenResourcesMapDefinition.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: WorldGenWorldDefinition): void {
    WorldGenWorldDefinition.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): WorldGenWorldDefinition {
    return WorldGenWorldDefinition.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


