/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BitcraftCargoItem {
  Name: string;
  Description: string;
  Volume: number;
  Tier: number;
  Rarity:
    | "default"
    | "common"
    | "uncommon"
    | "rare"
    | "epic"
    | "legendary"
    | "mythic";
  Tag: string;
  NotPickupable: boolean;
  BlocksPath: boolean;
  Id: string;
  Module?: string;
}
