name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm test:typecheck
      - name: Deploy Discord Commands
        run: pnpm discord:commands:deploy
        env:
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_ADMIN_GUILD_ID: ${{ secrets.DISCORD_ADMIN_GUILD_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract image tag
        id: meta
        run: |
          TAG=$(echo "${{ github.sha }}" | head -c 7)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest
